[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml; charset=utf-8"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"

[[redirects]]
  from = "/minecraft"
  to = "/minecraft/"
  status = 301
  force = true

[[redirects]]
  from = "/webhosting"
  to = "/webhosting/"
  status = 301
  force = true

[[redirects]]
  from = "/codehosting"
  to = "/codehosting/"
  status = 301
  force = true

[[redirects]]
  from = "/codeserver"
  to = "/codeserver/"
  status = 301
  force = true

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"
